// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: booksearch.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookName string `protobuf:"bytes,1,opt,name=bookName,proto3" json:"bookName,omitempty"`
	BookId   string `protobuf:"bytes,2,opt,name=bookId,proto3" json:"bookId,omitempty"`
}

func (x *BookInfo) Reset() {
	*x = BookInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booksearch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookInfo) ProtoMessage() {}

func (x *BookInfo) ProtoReflect() protoreflect.Message {
	mi := &file_booksearch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookInfo.ProtoReflect.Descriptor instead.
func (*BookInfo) Descriptor() ([]byte, []int) {
	return file_booksearch_proto_rawDescGZIP(), []int{0}
}

func (x *BookInfo) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *BookInfo) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type Answer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Availability bool `protobuf:"varint,1,opt,name=availability,proto3" json:"availability,omitempty"`
}

func (x *Answer) Reset() {
	*x = Answer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booksearch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_booksearch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_booksearch_proto_rawDescGZIP(), []int{1}
}

func (x *Answer) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

var File_booksearch_proto protoreflect.FileDescriptor

var file_booksearch_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x3e, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x32, 0x39, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x12, 0x2b, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x68, 0x65, 0x42, 0x6f,
	0x6f, 0x6b, 0x12, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x00,
	0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_booksearch_proto_rawDescOnce sync.Once
	file_booksearch_proto_rawDescData = file_booksearch_proto_rawDesc
)

func file_booksearch_proto_rawDescGZIP() []byte {
	file_booksearch_proto_rawDescOnce.Do(func() {
		file_booksearch_proto_rawDescData = protoimpl.X.CompressGZIP(file_booksearch_proto_rawDescData)
	})
	return file_booksearch_proto_rawDescData
}

var file_booksearch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booksearch_proto_goTypes = []interface{}{
	(*BookInfo)(nil), // 0: api.BookInfo
	(*Answer)(nil),   // 1: api.Answer
}
var file_booksearch_proto_depIdxs = []int32{
	0, // 0: api.BookSearch.FindTheBook:input_type -> api.BookInfo
	1, // 1: api.BookSearch.FindTheBook:output_type -> api.Answer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_booksearch_proto_init() }
func file_booksearch_proto_init() {
	if File_booksearch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_booksearch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booksearch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Answer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_booksearch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booksearch_proto_goTypes,
		DependencyIndexes: file_booksearch_proto_depIdxs,
		MessageInfos:      file_booksearch_proto_msgTypes,
	}.Build()
	File_booksearch_proto = out.File
	file_booksearch_proto_rawDesc = nil
	file_booksearch_proto_goTypes = nil
	file_booksearch_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BookSearchClient is the client API for BookSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookSearchClient interface {
	FindTheBook(ctx context.Context, in *BookInfo, opts ...grpc.CallOption) (*Answer, error)
}

type bookSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewBookSearchClient(cc grpc.ClientConnInterface) BookSearchClient {
	return &bookSearchClient{cc}
}

func (c *bookSearchClient) FindTheBook(ctx context.Context, in *BookInfo, opts ...grpc.CallOption) (*Answer, error) {
	out := new(Answer)
	err := c.cc.Invoke(ctx, "/api.BookSearch/FindTheBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookSearchServer is the server API for BookSearch service.
type BookSearchServer interface {
	FindTheBook(context.Context, *BookInfo) (*Answer, error)
}

// UnimplementedBookSearchServer can be embedded to have forward compatible implementations.
type UnimplementedBookSearchServer struct {
}

func (*UnimplementedBookSearchServer) FindTheBook(context.Context, *BookInfo) (*Answer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindTheBook not implemented")
}

func RegisterBookSearchServer(s *grpc.Server, srv BookSearchServer) {
	s.RegisterService(&_BookSearch_serviceDesc, srv)
}

func _BookSearch_FindTheBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookSearchServer).FindTheBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BookSearch/FindTheBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookSearchServer).FindTheBook(ctx, req.(*BookInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookSearch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.BookSearch",
	HandlerType: (*BookSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindTheBook",
			Handler:    _BookSearch_FindTheBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booksearch.proto",
}
